/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.VendaVeiculoController;
import javax.swing.JOptionPane;
import model.Veiculo;
import table.VendaVeiculoTableModel;

/**
 *
 * @author victor
 */
public class VendaPanel extends javax.swing.JPanel {

    private final VendaVeiculoController vendaVeiculoController;
    private final VendaVeiculoTableModel vendaVeiculoTableModel;

    /**
     * Creates new form VendaPanel
     */
    public VendaPanel(VendaVeiculoController controller, VendaVeiculoTableModel tableModel) {
        this.vendaVeiculoController = controller;
        this.vendaVeiculoTableModel = tableModel;

        // Constrói os componentes visuais (botões, tabelas, etc.)
        initComponents();
        
        // Vincula o modelo de dados correto (vendaVeiculoTableModel) à JTable
        tableVeiculosVenda.setModel(this.vendaVeiculoTableModel);
        
        // Carrega os dados iniciais na tabela
        this.vendaVeiculoController.atualizarTabela();
    }
    
    /**
     * Retorna o veículo selecionado na tabela.
     * @return O objeto Veiculo selecionado, ou null se nenhum for selecionado.
     */
    private Veiculo getVeiculoSelecionado() {
        int selectedRow = tableVeiculosVenda.getSelectedRow();
        if (selectedRow != -1) {
            // Converte o índice da linha da visão para o índice do modelo (importante para tabelas ordenadas)
            int modelRow = tableVeiculosVenda.convertRowIndexToModel(selectedRow);
            return this.vendaVeiculoTableModel.getVeiculo(modelRow);
        }
        return null;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVeiculosVenda = new javax.swing.JTable();
        btnVenderVeiculo = new javax.swing.JButton();

        jLabel1.setText("Veículos Disponíveis para Venda");

        tableVeiculosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableVeiculosVenda);

        btnVenderVeiculo.setText("Vender Veículo");
        btnVenderVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVenderVeiculo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenderVeiculo)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderVeiculoActionPerformed
        // TODO add your handling code here:
        Veiculo veiculo = getVeiculoSelecionado();

        if (veiculo == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um veículo para vender.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String msg = String.format("Deseja vender o veículo %s por R$%,.2f?",
                veiculo.getPlaca(), veiculo.getValorParaVenda());

        int confirm = JOptionPane.showConfirmDialog(this, msg, "Confirmar Venda", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                vendaVeiculoController.venderVeiculo(veiculo);
                JOptionPane.showMessageDialog(this, "Veículo vendido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                vendaVeiculoController.atualizarTabela(); // Atualiza a tabela
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao vender veículo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnVenderVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVenderVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVeiculosVenda;
    // End of variables declaration//GEN-END:variables
}
