/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.VendaVeiculoController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import model.Veiculo;
import service.VeiculoService;
import static service.VeiculoService.*;
import table.VeiculoTableModel;
import table.VendaVeiculoTableModel;

/**
 *
 * @author victor
 */
public class VendaPanel extends javax.swing.JPanel {

    private VendaVeiculoController controller;
    private VeiculoTableModel vendaVeiculoTableModel = new VendaVeiculoTableModel();
    private TableRowSorter<VeiculoTableModel> veiculoSorter;

    public VendaPanel() {
        initComponents();
        configurarSorterVeiculos();
        popularCombos();
    }

    /**
     * Retorna o veículo selecionado na tabela.
     *
     * @return O objeto Veiculo selecionado, ou null se nenhum for selecionado.
     */
    public Veiculo getVeiculoSelecionado() {
        int viewRow = tableVeiculosVenda.getSelectedRow();
        if (viewRow == -1) {
            return null;
        }
        int modelRow = tableVeiculosVenda.convertRowIndexToModel(viewRow);
        return vendaVeiculoTableModel.getVeiculo(modelRow);
    }

    private void configurarSorterVeiculos() {
        veiculoSorter = new TableRowSorter<>(vendaVeiculoTableModel);
        tableVeiculosVenda.setRowSorter(veiculoSorter);
        tableVeiculosVenda.setModel(vendaVeiculoTableModel);
    }

    private void popularCombos() {
        /* tipo (automóvel / moto / van)  */
        comboTipo.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        obterTiposVeiculo()
                )
        );

        /* marca (VW, GM, Fiat, …)  */
        comboMarca.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        obterMarcas()
                )
        );

        /* categoria (POPULAR, INTERMEDIARIO, LUXO)  */
        comboCategoria.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        obterCategorias()
                )
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVeiculosVenda = new javax.swing.JTable();
        btnVenderVeiculo = new javax.swing.JButton();
        checkboxFiltroCategoria = new javax.swing.JCheckBox();
        checkboxFiltroMarca = new javax.swing.JCheckBox();
        checkboxFiltroTipo = new javax.swing.JCheckBox();
        comboCategoria = new javax.swing.JComboBox<>();
        comboMarca = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        botaoPesquisarveiculos = new javax.swing.JButton();

        jLabel1.setText("Veículos Disponíveis para Venda");

        tableVeiculosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableVeiculosVenda);

        btnVenderVeiculo.setText("Vender Veículo");
        btnVenderVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderVeiculoActionPerformed(evt);
            }
        });

        checkboxFiltroCategoria.setText("Filtrar por Categoria");

        checkboxFiltroMarca.setText("Filtrar por Marca");

        checkboxFiltroTipo.setText("Filtrar por Tipo");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botaoPesquisarveiculos.setText("Pesquisar Veículos");
        botaoPesquisarveiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarveiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVenderVeiculo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkboxFiltroTipo)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkboxFiltroMarca)
                                    .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkboxFiltroCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoPesquisarveiculos)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxFiltroTipo)
                    .addComponent(checkboxFiltroMarca)
                    .addComponent(checkboxFiltroCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarveiculos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenderVeiculo)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderVeiculoActionPerformed
        controller.venderVeiculo();
    }//GEN-LAST:event_btnVenderVeiculoActionPerformed

    private void botaoPesquisarveiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarveiculosActionPerformed
        controller.listarVeiculosParaVenda();
    }//GEN-LAST:event_botaoPesquisarveiculosActionPerformed

    public void pesquisarVeiculosPublic() {
        controller.listarVeiculosParaVenda();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisarveiculos;
    private javax.swing.JButton btnVenderVeiculo;
    private javax.swing.JCheckBox checkboxFiltroCategoria;
    private javax.swing.JCheckBox checkboxFiltroMarca;
    private javax.swing.JCheckBox checkboxFiltroTipo;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVeiculosVenda;
    // End of variables declaration//GEN-END:variables

    public void setController(VendaVeiculoController controller) {
        this.controller = controller;

    }

    public void mostrarVeiculos(List<Veiculo> veiculos) {
        vendaVeiculoTableModel.setVeiculos(veiculos);
        tableVeiculosVenda.setModel(vendaVeiculoTableModel);
        tableVeiculosVenda.revalidate();
        tableVeiculosVenda.repaint();
    }

    public void aplicarFiltrosUI() {
        VeiculoService.aplicarFiltrosVeiculo(
                veiculoSorter,
                checkboxFiltroTipo,
                checkboxFiltroMarca,
                checkboxFiltroCategoria,
                comboCategoria,
                comboMarca,
                comboTipo
        );
    }

    public void limparSelecao() {
        tableVeiculosVenda.clearSelection();
    }

    public void apresentaInfo(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Informação", JOptionPane.INFORMATION_MESSAGE);
    }

    public void apresentaErro(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
